### ISSUE TITLE
文章管理 列表查询报错

### ISSUE THREAD

**Issue by xxt1998** [erupts/erupt-example#5]
![未定义的top字段排序](https://user-images.githubusercontent.com/38069341/147918297-e37e74a2-77b2-4017-9f94-1d9170bb935f.png)

**Comment by xxt1998** [comment]
`
SELECT
	new map (
		Article.pic AS pic,
		Article.content2 AS content2,
		Article.content AS content,
		Article.topUp AS topUp,
		Article.title AS title,
		Article.remark AS remark,
		Article.id AS id,
		Article.publish AS publish 
	) 
FROM
	Article AS Article 
WHERE
	1 = 1 
ORDER BY
	Article.top DESC
`

**Comment by erupts** [comment]
已修复，更新代码即可
